### ISSUE TITLE
Miner doesn't start on startup

### ISSUE THREAD

**Issue by ExplicitThinking** [UnamSanctam/SilentXMRMiner#57]
On the first try of even opening it, it says "You are attempting to open a type of file 'System file' (dll)". But on the second attempt to start up the built miner, it opens up fine, but when you restart your PC, it attempts to run the miner on startup but instead of it starting it brings up the same error message as trying to manually open the miner on the first try. I started experimenting and found this out after I noticed that all my workers were online but I was not mining anything.

Screenshot of the popup: https://gyazo.com/bafa55aba0f83666a484090b66407dda

**Comment by UnamSanctam** [comment]
Hmm, well that isn't normal, have you tried updating your Windows? That just to be a bug a long time ago.

**Comment by ExplicitThinking** [comment]
Just updated my windows to the latest version, the problem still persists, and I'm not getting any income from 7 workers.

**Comment by UnamSanctam** [comment]
Did you rebuild the miner after updating?

**Comment by ExplicitThinking** [comment]
Yep

**Comment by UnamSanctam** [comment]
Try building the miner on another computer if you have access to one and then try running it on your computer to see whether it is a problem with just building it or also running it.

**Comment by UnamSanctam** [comment]
And does the error occur if "Install" is disabled?

**Comment by ExplicitThinking** [comment]
No, actually it doesn't

**Comment by UnamSanctam** [comment]
Try disabling "Hide File" and see if it works.

**Comment by ExplicitThinking** [comment]
Ran it, restarted my pc and it brought up the error and when I checked task manager the miner wasn't running

**Comment by UnamSanctam** [comment]
Can you try to remove the miner first from the folder it's installed to and then run the miner that has "Hide File" disabled?

**Comment by ExplicitThinking** [comment]
Still gives the error on startup

**Comment by UnamSanctam** [comment]
Hmm, then there shouldn't really be anything wrong with the miner since the code is almost exactly the same when it's installed and not and it worked for you when it wasn't "installed". That error message used to be a general Windows bug like 6 months ago but it should be fixed if your computer is updated, 

Can you try running the "sfc /scannow" command in CMD to see if you have any corrupted Windows files?

Also can you list the settings in the "Main", "Install", and "Mining" tabs? You can take screenshots and attach them underneath the GitHub reply window if you find writing them down is too annoying.

**Comment by ExplicitThinking** [comment]
Well the error only shows when you restart your pc and it attempts to run on startup but it fails. I scanned and nothing came up, and my settings are below.
https://gyazo.com/e8ce0e021f64bb3a8dd8e08aa9dedc38

https://gyazo.com/771f69cfc433fdac9ce6755b35ba8684

**Comment by UnamSanctam** [comment]
Try choosing another Save Path like AppData (and don't forget to remove the old miner). Is there a reason you have Nicehash mining enabled? Do you use xmrig-proxy?

**Comment by ExplicitThinking** [comment]
Tried saving it in a different spot but the problems still there, also it's because I mine to a nicehash address.

**Comment by UnamSanctam** [comment]
Ah ok and the error also appears the first time you start the miner (not restarting)?

**Comment by ExplicitThinking** [comment]
Not on explorer, but on the rest I think so.

**Comment by UnamSanctam** [comment]
Well that shouldn't really make a difference unless you have some sort of permissions issues on your computer but that shouldn't even happen, also how do you currently check whether the miner is running or not?

**Comment by ExplicitThinking** [comment]
Task manager

**Comment by UnamSanctam** [comment]
You should use something like Process Explorer since it's harder to find it in the Task Manager because you have activated "Stealth" which pauses the miner while Task Manager is open.

**Comment by ExplicitThinking** [comment]
Yeah but I can tell because if I'm using explorer there are 2 explorers in the task manager and the miner is the one that takes more memory

**Comment by UnamSanctam** [comment]
Well yeah but then you won't know if it successfully connects to the pool and begins mining since you can't see the CPU usage.

**Comment by ExplicitThinking** [comment]
I can see it because it takes like 3 seconds before it completely goes down. So if I open task manager I can see it using cpu for a bit

**Comment by UnamSanctam** [comment]
Hmm, well anyways the problem is probably either with permissions or a service on your computer, the miner itself doesn't really do anything that special when "Install" is enabled as can be seen here: https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Program.vb

And what exactly did you mean by "my workers were online but I was not mining anything" in your first post? Do you mean online as in a RAT or something like that?

**Comment by ExplicitThinking** [comment]
No, just people that I sent the miner to and I confirmed that they opened it, im not getting any income at all towards my address.

**Comment by ExplicitThinking** [comment]
It seems like as soon as a day goes by I lose all my workers due to the miner not starting on startup

**Comment by UnamSanctam** [comment]
Have you tried building it another computer?

**Comment by ExplicitThinking** [comment]
No

**Comment by UnamSanctam** [comment]
Well if you can get access to another computer I would try to build one there since in all probability there is something wrong with a library or something similar on your computer. I could obviously build it for you but you might not trust me.

**Comment by ExplicitThinking** [comment]
I mean im already using your program so I don't see why not

**Comment by boff64** [comment]
I think that miner needs some kind of watch dog, it will be way better. It can check is it running, better hide from task manager, process can't be killed... and way more stable.

**Comment by UnamSanctam** [comment]
> I mean im already using your program so I don't see why not

Ok then I can build one with the settings you sent before, I would just need the pool address and wallet address, I'm not sure in what way you would like to send it.

> I think that miner needs some kind of watch dog, it will be way better. It can check is it running, better hide from task manager, process can't be killed... and way more stable.

Well a watchdog is already planned, only hard part is that it also has to be compiled when the miner is built and then embedded into the miner, since RunPE can't inject .NET binaries it would have to be made in something like C++ and be compiled by some sort of third-party library to work.

**Comment by boff64** [comment]
I know that you are busy now with your life problems, but please publish that update with anti sleep, greater stealth, watch dog(if you are planning to do that).... Also there is a problem in process hacker, user can just point mouse on explorer.exe and it shows mining parameters with pool, wallet and everything. I will pay for update, just publish it when you can.

**Comment by UnamSanctam** [comment]
I am about halfway done with most of the things in the update. And the parameters being exposed is kind of inevitable due to how Windows command line arguments work, all of the data would be able to be read using something like Wireshark anyways so hiding it isn't really possible in the first place.

**Comment by ExplicitThinking** [comment]
Wallet: 89TgyjLcWrghRe5NLW37UeTDZGA9sjuNJg69hYd9uRgtjX9HvFDaR1xHVWTERzqx62MCV6fNZpDMaZDvQRNUDmEs7C7xJxS

Pool: xmr-us-west1.nanopool.org:14433

Try making a mega link

**Comment by UnamSanctam** [comment]
Ok I'll build one, also on nanopool Nicehash shouldn't be enabled so I won't enable that.

**Comment by UnamSanctam** [comment]
Do you want me to obfuscate the file as well or do you just want the raw file?

**Comment by ExplicitThinking** [comment]
Does it matter?

**Comment by UnamSanctam** [comment]
Well obfuscated files are less detectable since it "scrambles" a lot of the code and adds other things to bypass antivirus scans.

**Comment by ExplicitThinking** [comment]
K go for it

**Comment by UnamSanctam** [comment]
Here's the link: https://mega.nz/file/6aJhlILJ#yhB1ODMmRety7nucDJaeG4DcuHSN7zl6Ng6ri8308lk I have tested everything and it was all working.

**Comment by ExplicitThinking** [comment]
It worked, I guess it was a problem on my part... Thanks for being so patient though

**Comment by UnamSanctam** [comment]
No problem, I'm glad it worked out at least.

**Comment by iml1929** [comment]
Hi and thank you for this great project, just wondering any news on the update you mentioned?

> I am about halfway done with most of the things in the update. And the parameters being exposed is kind of inevitable due to how Windows command line arguments work, all of the data would be able to be read using something like Wireshark anyways so hiding it isn't really possible in the first place.

**Comment by UnamSanctam** [comment]
Anti-sleep and hiding the command window and a watchdog has now been added in the new version.
